// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shipping_Form_CreatorV1.Data;

#nullable disable

namespace Shipping_Form_CreatorV1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineItemHeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineItemHeaderId")
                        .IsUnique();

                    b.HasIndex("ReportModelId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.LineItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BolFlag")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ModelItem")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NoteSequenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackingListFlag")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LineItemId");

                    b.ToTable("LineItemDetails");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.LineItemHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BackOrderQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineItemNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PickOrShipQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LineItemHeaders");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.LineItemPackingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CartonOrSkid")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeOfUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineItemId");

                    b.ToTable("LineItemPackingUnits");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.ReportHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPONumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FreightTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrdEnterDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipToCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipToCustAddressLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipToCustAddressLine2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipToCustAddressLine3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipToCustNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipToName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipToSt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipToZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingInstructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldToCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldToCustAddressLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldToCustAddressLine2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldToCustAddressLine3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldToCustNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldToName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldToSt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldToZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportModelId")
                        .IsUnique();

                    b.ToTable("ReportHeaders");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.ReportModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportHeaderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReportModels");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.LineItem", b =>
                {
                    b.HasOne("Shipping_Form_CreatorV1.Models.LineItemHeader", "LineItemHeader")
                        .WithOne()
                        .HasForeignKey("Shipping_Form_CreatorV1.Models.LineItem", "LineItemHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shipping_Form_CreatorV1.Models.ReportModel", "ReportModel")
                        .WithMany("LineItems")
                        .HasForeignKey("ReportModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineItemHeader");

                    b.Navigation("ReportModel");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.LineItemDetail", b =>
                {
                    b.HasOne("Shipping_Form_CreatorV1.Models.LineItem", "LineItem")
                        .WithMany("LineItemDetails")
                        .HasForeignKey("LineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineItem");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.LineItemPackingUnit", b =>
                {
                    b.HasOne("Shipping_Form_CreatorV1.Models.LineItem", "LineItem")
                        .WithMany("LineItemPackingUnits")
                        .HasForeignKey("LineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineItem");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.ReportHeader", b =>
                {
                    b.HasOne("Shipping_Form_CreatorV1.Models.ReportModel", "ReportModel")
                        .WithOne("Header")
                        .HasForeignKey("Shipping_Form_CreatorV1.Models.ReportHeader", "ReportModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportModel");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.LineItem", b =>
                {
                    b.Navigation("LineItemDetails");

                    b.Navigation("LineItemPackingUnits");
                });

            modelBuilder.Entity("Shipping_Form_CreatorV1.Models.ReportModel", b =>
                {
                    b.Navigation("Header")
                        .IsRequired();

                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
